"""Build report/report_draft.md: per-task comparison tables (both members, every required metric), evidence links
and the report skeleton. All numbers are read from the members' committed CSV / JSON files - nothing is typed in.
Sections that must be written by the team are marked TODO(team).

usage: python report/build_report_draft.py
"""
import csv
import json
from pathlib import Path

REPO = Path(__file__).resolve().parents[1]
REPO_URL = "https://github.com/ChaitanyaUppalapati/Lab_Pair_18"


def rows(path):
    with open(REPO / path, encoding="utf-8") as f:
        return list(csv.DictReader(f))


def f(v, nd=4):
    try:
        x = float(v)
    except (TypeError, ValueError):
        return v if v not in (None, "") else "—"
    if x != x:
        return "—"
    if abs(x) >= 1e5:
        return f"{x:,.0f}"
    return f"{x:,.{nd}f}"


def table(header, body):
    out = ["| " + " | ".join(header) + " |", "|" + "---|" * len(header)]
    out += ["| " + " | ".join(str(c) for c in r) + " |" for r in body]
    return out


def transpose(names, body):
    """body: rows of [metric label, value per model ...]"""
    return table(["Metric"] + names, body)


md = []
add = md.extend

# --------------------------------------------------------------------------------------------- front matter
add([
    "# DATA266 Lab 1 — Team 18 report (DRAFT)", "",
    f"Repository: {REPO_URL}", "",
    "> Draft generated by `report/build_report_draft.py` from the committed metrics files. Tables and evidence links",
    "> are filled automatically; every **TODO(team)** section must be written by the team. Export the final version",
    "> to `report/DATA266_Lab1_Report_Team_18.pdf`.", "",
    "## Team ownership statement", "",
    "TODO(team): one paragraph, who built what. Facts recorded in the repository that the statement must agree with:",
    "- Chaitanya: all Task 1–3 code in `member_chaitanya/` was written by Claude (AI assistant) from Chaitanya's",
    "  design decisions; for Task 3, design decisions from run 5 onward were made by Claude with Chaitanya's",
    "  authorisation and are marked **[Claude]** in `task3_gan/member_chaitanya/DESIGN_LOG.md`.",
    "- Aswin: TODO(Aswin) — describe your own process the same way.", "",
])

# --------------------------------------------------------------------------------------------- Task 1
c1 = rows("task1_llm/member_chaitanya/metrics_report.csv")[0]
a1 = [r for r in rows("task1_llm/member_aswin/metrics_report.csv") if r.get("run_type") == "full"]
a1 = a1[0] if a1 else None
pend = "pending (full run not in repo)"
add(["## Task 1 — Character-level GPT on TinyStories", "", "### Comparison table", ""])
add(table(["", "Chaitanya (full_run01)", "Aswin"], [
    ["Data", "100K / 10K stories (cleaned, deduplicated), sliding windows, stride 128, `<EOS>` between stories",
     "100K / 10K stories, one seeded crop per story, `<BOS>`/`<EOS>`/`<PAD>`"],
    ["Architecture", "Pre-LN decoder, 6 layers, 6 heads (64-d), d_model 384, FFN 1536 (GELU), learned positions, untied head",
     "Pre-LN decoder, 5 layers, 6 heads (40-d), d_model 240, FFN 960 (GELU), learned positions"],
    ["Context", "256", "160"],
    ["Dropout", "0.1", "0.12"],
    ["Optimiser", "AdamW (0.9, 0.99), wd 0.1 on 2-D weights", "AdamW, wd 0.1"],
    ["LR schedule", "peak 1e-3, 1,000-step warm-up, cosine to 1e-4", "peak 2.5e-4, 5% warm-up, cosine to 10%"],
    ["Batch / epochs", "64 × 256 / 10", "48 / 12"],
    ["Grad clipping", "1.0", "1.0"],
]))
add(["", "Metrics (Chaitanya: validation set of 10K stories; generation metrics at temperature 0.8):", ""])
keys = [("Training CE loss", "train_ce_loss"), ("Validation CE loss", "val_ce_loss"), ("Perplexity", "perplexity"),
        ("Bits per character", "bits_per_char"), ("Generalisation gap (val − train)", "generalization_gap"),
        ("Top-1 next-char accuracy", "top1_next_char_acc"), ("Distinct-1", "distinct_1"), ("Distinct-2", "distinct_2"),
        ("Distinct-3", "distinct_3"), ("Repeated 4-gram rate", "repeated_4gram_rate"),
        ("Max / mean grad norm", None), ("Loss spikes / NaNs", None), ("Parameters", "param_count"),
        ("Train tokens/s", "train_tokens_per_sec"), ("Generation tokens/s", "gen_tokens_per_sec"),
        ("Peak memory (MB)", "peak_memory_mb"), ("Total training time (s)", "total_train_time_s"), ("Hardware", "hardware")]
body = []
for lab, k in keys:
    if lab.startswith("Max / mean"):
        mine = f"{f(c1['max_grad_norm'], 2)} / {f(c1['mean_grad_norm'], 3)}"
        his = f"{f(a1['max_grad_norm'], 2)} / {f(a1['mean_grad_norm'], 3)}" if a1 else pend
    elif lab.startswith("Loss spikes"):
        mine = f"{c1['loss_spikes']} / {c1['nan_count']}"
        his = f"{a1['loss_spikes']} / {a1['nan_count']}" if a1 else pend
    else:
        mine = f(c1[k]) if k != "hardware" else c1[k]
        his = (f(a1[k]) if k != "hardware" else a1[k]) if a1 else pend
    body.append([lab, mine, his])
add(transpose(["Chaitanya", "Aswin"], body))
add(["", "Note: Aswin's distinct-n counts character n-grams; Chaitanya's counts word n-grams — not directly comparable.",
     "", "### Joint analysis", "", "TODO(team): strengths, weaknesses, limitations, what the team would try next.", "",
     "### Evidence", "",
     "- Chaitanya: loss curves `task1_llm/member_chaitanya/outputs/full_run01/loss_curves.png`, stability "
     "`.../stability.png`, samples `.../samples.txt`, raw log `reproducibility/raw_logs/task1_llm/chaitanya/full_run01.log`, "
     "manifest `reproducibility/manifests/task1_llm/chaitanya/`, checkpoint `full_run01/final.pt`, notebook "
     "`task1_llm/member_chaitanya/src/task1_chaitanya.ipynb`.",
     "- Aswin: TODO(Aswin) after the full run.", "",
     "### Failure analysis", "",
     "- Chaitanya: `task1_llm/member_chaitanya/failure_analysis.md` (paste the 3 cases with their text here).",
     "- Aswin: `task1_llm/member_aswin/failure_analysis.md`.", ""])

# --------------------------------------------------------------------------------------------- Task 2
c2 = [r for r in rows("task2_sentiment/member_chaitanya/metrics_report.csv") if r["eval_set"] == "test5k"]
a2 = rows("task2_sentiment/member_aswin/metrics_report.csv")
seed = {r["model"]: r for r in rows("task2_sentiment/member_chaitanya/outputs/seed_summary.csv") if r["eval_set"] == "test5k"}
names = ["C: Baseline (fastText bigram)", "C: Exp 1 (HAN)", "C: Exp 2 (Transformer)",
         "A: Baseline (mean-pool FFN)", "A: Exp 1 (BiGRU)", "A: Exp 2 (TextCNN)"]
mine = [r for r in c2 if not r["model"].startswith("Reference")]
allm = mine + a2
add(["## Task 2 — Yelp Polarity sentiment (no pretrained embeddings or LMs)", "",
     "Both members use the **same rows**: train 20K / validation 5K / test 5K (Aswin's split; HF row indices in "
     "`task2_sentiment/member_chaitanya/splits/`, verified against Aswin's predictions). All metrics below are on the "
     "shared 5K test set, threshold 0.5. C = Chaitanya, A = Aswin.", "", "### Architectures and hyperparameters", ""])
add(table(["Model", "Architecture", "Embedding", "Key hyperparameters"], [
    [names[0], "mean of unigram + hashed-bigram (2^17) embeddings → linear", "128-d, scratch", "AdamW 3e-3, wd 0.01, batch 64, ≤20 ep, patience 3, emb. dropout 0.3"],
    [names[1], "word BiLSTM + attention → sentence BiLSTM + attention → linear (32 × 32 input)", "128-d, scratch", "AdamW 1e-3, wd 0.01, batch 64, ≤15 ep, patience 3, dropout 0.3, clip 1.0"],
    [names[2], "2-layer, 4-head, width-128 pre-LN Transformer encoder (hand-written), masked mean pool", "128-d, scratch + learned positions", "AdamW 5e-4, 5% warm-up + linear decay, wd 0.01, batch 64, ≤20 ep, dropout 0.1/0.2, clip 1.0"],
    [names[3], "mean pooling → Dense(128) → ReLU → Dropout(0.3) → Dense(1)", "128-d, scratch", "AdamW 1e-3, wd 1e-4, batch 64, ≤5 ep, ReduceLROnPlateau"],
    [names[4], "1-layer BiGRU (128) → max + mean pooling → Dense(128) → Dropout(0.4) → Dense(1)", "128-d, scratch", "AdamW 5e-4, wd 1e-4, batch 64, ≤5 ep, ReduceLROnPlateau"],
    [names[5], "TextCNN, filters 3/4/5 × 100 → max-over-time → Dense(128) → Dropout(0.4) → Dense(1)", "128-d, scratch", "AdamW 1e-3, wd 1e-4, batch 64, ≤5 ep, ReduceLROnPlateau"],
]))
add(["", "Preprocessing differs between members (a known confound): Chaitanya lemmatises (POS-aware), expands "
     "contractions and keeps not/no/nor/never/but/however/very/too/few/against, min frequency 2 (vocab 19,646); Aswin "
     "keeps ≈33 negation forms but removes but/however/very/too/few, no lemmatisation, min frequency 3 (vocab 18,766).",
     "", "### Metrics (shared 5K test set)", ""])
mm = [("Accuracy", "accuracy"), ("Accuracy 95% CI", ("acc_ci_low", "acc_ci_high")),
      ("Precision (macro)", "precision_macro"), ("Recall (macro)", "recall_macro"), ("F1 (macro)", "f1_macro"),
      ("F1 macro 95% CI", ("f1_macro_ci_low", "f1_macro_ci_high")), ("Precision / recall / F1 (micro)", ("precision_micro", "recall_micro", "f1_micro")),
      ("Precision / recall / F1 (weighted)", ("precision_weighted", "recall_weighted", "f1_weighted")),
      ("Confusion matrix TN / FP / FN / TP", ("tn", "fp", "fn", "tp")), ("ROC-AUC", "roc_auc"), ("PR-AUC", "pr_auc"),
      ("MCC", "mcc"), ("MCC 95% CI", ("mcc_ci_low", "mcc_ci_high")), ("Brier score", "brier"), ("ECE", "ece"),
      ("McNemar vs own baseline (χ², p)", ("mcnemar_vs_baseline_stat", "mcnemar_vs_baseline_p")),
      ("Parameters", "param_count"), ("Training time (s)", "train_time_s"), ("Training examples/s", "examples_per_sec"),
      ("Peak memory (MB)", "peak_memory_mb"), ("Hardware", "hardware")]
body = []
for lab, k in mm:
    vals = []
    for r in allm:
        if isinstance(k, tuple):
            parts = [f(r.get(x), 0 if x in ("tn", "fp", "fn", "tp") else 4) for x in k]
            v = (f"[{parts[0]}, {parts[1]}]" if "CI" in lab else " / ".join(parts))
            if lab.startswith("McNemar") and parts[0] == "—":
                v = "—"
        else:
            v = r.get(k, "—") if k == "hardware" else f(r.get(k), 0 if k == "param_count" else (1 if k in ("train_time_s", "examples_per_sec", "peak_memory_mb") else 4))
        vals.append(v)
    body.append([lab] + vals)
body.append(["Seeds", "42, 43, 44 (seed 42 shown)"] * 1 + ["42, 43, 44 (seed 42 shown)"] * 2 + ["42 (single run)"] * 3)
body.append(["Accuracy over seeds (mean ± std)"] + [
    f"{float(seed[r['model']]['accuracy_mean']):.4f} ± {float(seed[r['model']]['accuracy_std']):.4f}" for r in mine] + ["—"] * 3)
add(transpose(names, body))
tm = rows("task2_sentiment/member_chaitanya/outputs/team_mcnemar.csv")
add(["", "Slices (macro-F1 and error rate per slice for all six models, on both members' slice definitions): "
     "`task2_sentiment/member_chaitanya/outputs/slice_metrics.csv`; Chaitanya's extra 33K test set: "
     "`task2_sentiment/member_chaitanya/metrics_report.csv` (eval_set = test33k).", "",
     "### Team McNemar tests (5K test set, Holm-corrected over 9 pairs)", ""])
add(table(["Chaitanya model", "Aswin model", "C right / A wrong", "C wrong / A right", "p", "p (Holm)"],
          [[r["model_a"], r["model_b"], r["a_right_b_wrong"], r["a_wrong_b_right"], f(r["p_value"]), f(r["p_holm"])] for r in tm]))
add(["", "### Joint analysis", "", "TODO(team): strengths, weaknesses, limitations, what the team would try next.", "",
     "### Evidence", "",
     "- Chaitanya: training curves `task2_sentiment/member_chaitanya/outputs/plots/training_curves.png`; ROC / PR / "
     "reliability `.../plots/roc_pr_reliability_test5k.png`; confusion matrices `.../plots/confusion_matrices_test5k.png`; "
     "raw logs `reproducibility/raw_logs/task2_sentiment/chaitanya/`; manifests `reproducibility/manifests/task2_sentiment/chaitanya/`; "
     "checkpoint IDs `t2_baseline_s42`, `t2_exp1_han_s42`, `t2_exp2_transformer_s42` (+ seeds 43, 44); predictions "
     "`task2_sentiment/member_chaitanya/outputs/runs/<id>/`; notebook `task2_sentiment/member_chaitanya/src/task2_chaitanya.ipynb`.",
     "- Aswin: plots `task2_sentiment/member_aswin/outputs/plots/`, confusion matrices `.../confusion_matrices/`, "
     "calibration `.../calibration/`, predictions `.../predictions/`, notebook `task2_sentiment/member_aswin/src/task2_sentiment_aswin.ipynb`.",
     "", "### Error review", "",
     "- Chaitanya: `task2_sentiment/member_chaitanya/failure_analysis.md` (20 errors of the baseline; paste with text snippets).",
     "- Aswin: `task2_sentiment/member_aswin/failure_analysis.md`, `outputs/error_analysis/error_analysis.csv`.", ""])

# --------------------------------------------------------------------------------------------- Task 3
c3 = {(r["run_id"], r["direction"][:3]): r for r in rows("task3_gan/member_chaitanya/full_metrics_report.csv")}
fin_b, fin_a = c3[("full_run18", "B2A")], c3[("full_run18", "A2B")]
r1_b, r1_a = c3[("full_run01", "B2A")], c3[("full_run01", "A2B")]
off = json.loads((REPO / "task3_gan/member_chaitanya/outputs/official_eval.json").read_text())
add(["## Task 3 — CycleGAN Monet ↔ photo (Kaggle)", "",
     "Naming follows Kaggle: A = Monet, B = photo. Kaggle score = −(FID + MiFID)/2 with the instructor's script "
     "(first 300 images per folder, both directions).", "", "### Architectures and hyperparameters", ""])
add(table(["", "Chaitanya run 1 (own design)", "Chaitanya submitted model (runs 2 → 18)", "Aswin v3 (submitted)"], [
    ["Generator", "ResNet-9, 64 filters, nearest-neighbour upsample + conv, InstanceNorm, reflection padding", "same", "ResNet-9, 64 filters, nearest-neighbour resize-conv, InstanceNorm, reflection padding"],
    ["Discriminator", "70×70 PatchGAN (1 scale)", "G_A2B trained with 1-scale D; G_B2A with 2-scale PatchGAN (runs 10+)", "70×70 PatchGAN, 1 scale (notebook config; results.md says 2-scale spectral-norm — Aswin to reconcile)"],
    ["Loss", "LSGAN, D loss × 0.5", "same", "LSGAN"],
    ["λ_cycle / λ_identity", "10 / 5", "2 / 0 (10/5 → 5/0.5 → 2/0, runs 6–7)", "10 / 2.5 decaying to 0.5"],
    ["Augmentation", "resize 286 → crop 256, h-flip", "+ DiffAugment (translation + cutout) on both D; G_B2A fine-tuned at 256 (no zoom)", "resize 287 → crop 256, h-flip; DiffAugment p 0.8; R1 (γ 0.5)"],
    ["Optimiser / LR", "Adam 2e-4 (0.5, 0.999); constant 20 ep + linear decay 20 ep", "warm restarts 1e-4 … 1.5e-5 → 0 on top of run 1's schedule (126 epochs total for G_B2A)", "Adam G 2e-4 / D 1e-4 (0.5, 0.999); 150 ep, decay from 75; checkpoint epoch 90 submitted"],
    ["Stabilisers", "50-image pool", "50-image pool, generator EMA 0.9999, per-direction weight averaging (soups)", "50-image pool, AMP, grad clip 10, EMA 0.999"],
    ["Batch / precision", "1 / fp32", "1 / fp32", "1 / AMP"],
]))
add(["", "### Metrics", ""])
aswin_off = {"B2A": ("103.126", "0.4077"), "A2B": ("119.646", "0.4348")}
mt = [("FID (official script, 300 images)", None),
      ("MiFID (official script)", None),
      ("FID (torchmetrics, all images)", "fid"), ("KID mean ± std", ("kid_mean", "kid_std")),
      ("Generative precision / recall", ("gen_precision", "gen_recall")), ("Density / coverage", ("density", "coverage")),
      ("Cycle-reconstruction L1", "cycle_l1"), ("LPIPS (input vs translation)", "lpips"),
      ("Content cosine similarity", "content_cosine_sim"), ("Final G / D loss", ("final_g_loss", "final_d_loss")),
      ("Cycle / identity loss", ("cycle_loss", "identity_loss")), ("Max gradient norm / NaN count", ("max_grad_norm", "nan_count")),
      ("Human audit style / content / artifacts", ("human_style", "human_content", "human_artifacts")),
      ("Inter-rater κ / % agreement", ("inter_rater_kappa", "pct_agreement")), ("Parameters (one G)", "param_count"),
      ("Training time (s)", "train_time_s"), ("Images/s", "images_per_sec"), ("Peak memory (MB)", "peak_memory_mb")]
body = []
for lab, k in mt:
    vals = []
    for run, d in (("full_run01", "A2B"), ("full_run01", "B2A"), ("full_run18", "A2B"), ("full_run18", "B2A")):
        r = c3[(run, d)]
        if k is None:
            o = off if run == "full_run18" else min(json.loads((REPO / "task3_gan/member_chaitanya/outputs/full_run01/snapshot_scores_official.json").read_text()), key=lambda e: e["FID"])
            vals.append(f(o[("FID_" if lab.startswith("FID") else "MiFID_") + d]))
        elif isinstance(k, tuple):
            vals.append(" / ".join(f(r.get(x)) if r.get(x) not in ("", None) else "pending" for x in k))
        else:
            vals.append(f(r.get(k)) if k != "param_count" else f(r.get(k), 0))
    if lab.startswith("FID (official"):
        vals += [aswin_off["A2B"][0], aswin_off["B2A"][0]]
    elif lab.startswith("MiFID"):
        vals += [aswin_off["A2B"][1], aswin_off["B2A"][1]]
    else:
        vals += ["pending (v3 not evaluated)"] * 2
    body.append([lab] + vals)
add(transpose(["C run 1 A2B", "C run 1 B2A", "C final A2B", "C final B2A", "A v3 A2B", "A v3 B2A"], body))
sub = (REPO / "task3_gan/member_chaitanya/submission.csv").read_text().strip().splitlines()[-1].split(",")
asub = (REPO / "task3_gan/member_aswin/submission.csv").read_text().strip().splitlines()[-1].split(",")
add(["", "Official per-direction values for Chaitanya: `task3_gan/member_chaitanya/outputs/full_run18/snapshot_scores.csv` "
     "(epoch_123_ema: FID A2B 97.81, B2A 94.21). Run-1 columns use the per-snapshot rescoring of epoch 40 (mean FID 107.33); the submitted run-1 entry, scored from the final-model export, was FID 107.25 / MiFID 0.4148 → −53.83.", "",
     "### Kaggle", ""])
add(table(["Member", "Submission FID", "Submission MiFID", "Score −(FID+MiFID)/2", "Public LB", "Private LB", "Rank"], [
    ["Chaitanya (team submission)", f(sub[1]), f(sub[2]), f(-(float(sub[1]) + float(sub[2])) / 2), "−48.2029",
     "TODO (after competition close)", "TODO (≈16 of 44 once the non-official −42.1653 entry is removed)"],
    ["Aswin", f(asub[1]), f(asub[2]), f(-(float(asub[1]) + float(asub[2])) / 2), "not submitted", "—", "—"],
]))
add(["", "Note: an earlier team entry of −42.1653 was computed with a non-official protocol before the evaluation script "
     "was available; the host was asked to invalidate it (see `task3_gan/member_chaitanya/results.md`, Kaggle section).",
     "", "### Joint analysis", "", "TODO(team): strengths, weaknesses, limitations, what the team would try next.", "",
     "### Evidence", "",
     "- Chaitanya: design log with every change and its official score `task3_gan/member_chaitanya/DESIGN_LOG.md`; loss "
     "curves `task3_gan/member_chaitanya/outputs/full_run*/loss_curves.png`; sample grids `outputs/full_run*/grids/`; "
     "official scores per snapshot `outputs/full_run*/snapshot_scores.csv`; raw logs `reproducibility/raw_logs/task3_gan/chaitanya/`; "
     "manifests `reproducibility/manifests/task3_gan/chaitanya/`; submitted checkpoint `checkpoints/full_run18/epoch_123_ema/`; "
     "notebook `task3_gan/member_chaitanya/src/task3_chaitanya.ipynb`.",
     "- Aswin: `task3_gan/member_aswin/src/task3_cyclegan_aswin_v3.ipynb`, `src/Part3_Evaluation_Script_evaluated.ipynb`, "
     "checkpoint `aswin_cyclegan_v3_improved/epoch_090.pt`.", "",
     "### Failure analysis and human audit", "",
     "- Chaitanya: `task3_gan/member_chaitanya/failure_analysis.md` (paste the 3 image strips); human audit "
     "`task3_gan/member_chaitanya/outputs/human_audit/` (pending ratings).",
     "- Aswin: `task3_gan/member_aswin/failure_analysis.md`.", "",
     "## References", "",
     "- Vaswani, A. et al. (2017). Attention Is All You Need. NeurIPS.",
     "- Eldan, R., & Li, Y. (2023). TinyStories: How Small Can Language Models Be and Still Speak Coherent English? arXiv:2305.07759.",
     "- Zhu, J.-Y., Park, T., Isola, P., & Efros, A. A. (2017). Unpaired Image-to-Image Translation using Cycle-Consistent Adversarial Networks. ICCV.",
     "- Yang, Z. et al. (2016). Hierarchical Attention Networks for Document Classification. NAACL.",
     "- Joulin, A. et al. (2017). Bag of Tricks for Efficient Text Classification. EACL.",
     "- Zhao, S. et al. (2020). Differentiable Augmentation for Data-Efficient GAN Training. NeurIPS.",
     "- Zhang, X., Zhao, J., & LeCun, Y. (2015). Character-level Convolutional Networks for Text Classification (Yelp Polarity). NeurIPS.",
     ""])

(REPO / "report" / "report_draft.md").write_text("\n".join(md), encoding="utf-8")
print("wrote report/report_draft.md")
